#!/usr/bin/python3

import pexpect.fdpexpect
import serial
import sys

s = serial.Serial('/dev/ttyAMA1', 115200)
console = pexpect.fdpexpect.fdspawn(s)

down = "\x1b[B"

console.logfile = sys.stdout.buffer
console.expect("F2 or Down")
console.send(down)
console.expect_exact("Continue")
while console.expect_exact(["\x1b[37m\x1b[40m\x1b[11;04HBoot Manager", pexpect.TIMEOUT], timeout=1) == 1:
    console.send(down)
console.send("\r")

menu_entry = sys.argv[1]
retries = 5
while console.expect(["\x1b\\[37m\x1b\\[40m\x1b\\[\\d+;\\d+H[a-zA-Z0-9 ]*{}".format(menu_entry), pexpect.TIMEOUT], timeout=1) == 1:
    console.send(down)
    retries -= 1
    if not retries:
        print("Failed to find '{}' menu entry".format(menu_entry), file=sys.stderr)
        sys.exit(1)
console.send("\r")
