#!/bin/sh

ssh -o UserKnownHostsFile=/usr/local/openqa-cmds/thor-known-hosts control@thor poweroff
sudo $(dirname "$0")/mount-iso ""
sudo systemctl stop gadget-control.service
# wait to be sure, some capacitor might still keep it up
sleep 3
rm -f /tmp/is-power-on
